### ISSUE TITLE
Updating packages + lockfile breaks deployment

### ISSUE THREAD

**Issue by justin-hackin** [robipop22/dnb-stack#107]
I added my vercel secrets, changes the `dnb-stack` url aliases, and the stack deploys successfully.

 When I run `bun install` and push the lock file, the deploy install step is broken.

```
[15:18:03.875] Running build in Washington, D.C., USA (East) – iad1
[15:18:04.076] Retrieving list of deployment files...
[15:18:04.624] Downloading 57 deployment files...
[15:18:09.916] Restored build cache
[15:18:09.983] Running "vercel build"
[15:18:10.862] Vercel CLI 33.6.1
[15:18:11.547] Installing dependencies...
[15:18:11.586] bun install v1.0.35 (940448d6)
[15:18:11.997] /vercel/path0/node_modules/vite/node_modules/esbuild/install.js:133
[15:18:11.997]     throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
[15:18:11.998]           ^
[15:18:11.998] 
[15:18:11.998] Error: Expected "0.19.12" but got "0.17.6"
[15:18:11.998]     at validateBinaryVersion (/vercel/path0/node_modules/vite/node_modules/esbuild/install.js:133:11)
[15:18:11.998]     at /vercel/path0/node_modules/vite/node_modules/esbuild/install.js:286:5
[15:18:11.998] 
[15:18:11.998] Node.js v20.11.1
[15:18:11.998] 
[15:18:11.998] error: postinstall script from "esbuild" exited with 1
[15:18:12.006] Error: Command "bun install" exited with 1
[15:18:12.635] 
```

**Comment by robipop22** [comment]
are you still encountering this ? if so please try to update and open a new issue, I'm going to close this one.
